name = "spinmachoapp-com-gr"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=spinmachoapp.com.gr"
HMAC_KEY = "6e5a9d8f9660f6a58423e2546ed51da763554a8b0572cf60b45ba2b1aa16f230"
COOKIE_NAME = "hv1"
PLAY_PATH = "visit"
BUTTON_ID = "pf3948d31b3e636f85ae26de7b22664b3"
GATE_SALT = "97e8c2b5523e223a"
